dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - wget -N 
  - http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver/usr/local/bin/chromedriver
  - sleep 3
  - "export DISPLAY=99:0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install selenium
  - pip install codacy-coverage
script:
  - cd decide
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.27.0-linux64.tar.gz
  - chmod +x geckodriver 
  - sudo cp geckodriver /usr/bin/
  - rm geckodriver-v0.27.0-linux64.tar.gz
  - cp travis_local_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decide-single-verde-votaciones
  strategy: git
  api_key: bc5548c4-bd7e-40d3-866c-4a1473f1f439
