# Generated by Django 2.0 on 2021-01-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='answer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='preference',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Mid'), ('L', 'Low')], max_length=4),
        ),
    ]
