# Generated by Django 2.0 on 2021-01-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_voting_themevotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='themeVotation',
            field=models.CharField(choices=[('El', 'Electoral'), ('Si', 'Self-interest'), ('Kw', 'Knowledge'), ('Ts', 'Testing'), ('Su', 'Survey')], max_length=4),
        ),
    ]
