# Generated by Django 2.0 on 2021-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20210116_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='themeVotation',
            field=models.CharField(choices=[('El', 'Electoral'), ('Si', 'Self-interest'), ('Kw', 'Knowledge'), ('Ts', 'Testing'), ('Su', 'Survey')], max_length=14),
        ),
    ]
