# Generated by Django 2.0 on 2021-01-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_question_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scopes',
            field=models.TextField(blank=True, choices=[('Lit', 'Literature'), ('Ent', 'Entertainment'), ('Geo', 'Geography'), ('His', 'History'), ('Sci', 'Science'), ('Spo', 'Sports'), ('Oth', 'Other')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='preference',
            field=models.TextField(choices=[('H', 'High'), ('M', 'Mid'), ('L', 'Low')], max_length=14),
        ),
        migrations.AlterField(
            model_name='voting',
            name='themeVotation',
            field=models.TextField(choices=[('El', 'Electoral'), ('Si', 'Self-interest'), ('Kw', 'Knowledge'), ('Ts', 'Testing'), ('Su', 'Survey')], max_length=14),
        ),
    ]
