import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTallyExport(StaticLiveServerTestCase):

    def setup_method(self, method):
        self.vars = {}
        self.usernameDecide = 'admin'
        self.passwordDecide = 'adminpass'

        options = webdriver.FirefoxOptions()
        options.headless = True
        driver = webdriver.Firefox(options=options)

    def teardown_method(self, method):
        self.driver.quit()

    def test_testrestartvoting(self):
        self.driver.get("http://localhost:8000/admin/")
        self.driver.set_window_size(957, 727)
        self.driver.find_element(By.ID, "id_username").send_keys(self.usernameDecide)
        self.driver.find_element(By.ID, "id_password").send_keys(self.passwordDecide)
        self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
        self.driver.find_element(By.LINK_TEXT, "Questions").click()
        self.driver.find_element(By.CSS_SELECTOR, ".addlink").click()
        self.driver.find_element(By.ID, "id_desc").send_keys("desc question test")
        self.driver.find_element(By.ID, "id_scopes").click()
        dropdown = self.driver.find_element(By.ID, "id_scopes")
        dropdown.find_element(By.XPATH, "//option[. = 'Literature']").click()
        self.driver.find_element(By.ID, "id_scopes").click()
        self.driver.find_element(By.ID, "id_options-0-number").click()
        self.driver.find_element(By.ID, "id_options-0-number").click()
        element = self.driver.find_element(By.ID, "id_options-0-number")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "id_options-0-number").send_keys("1")
        self.driver.find_element(By.ID, "id_options-0-option").click()
        self.driver.find_element(
            By.ID, "id_options-0-option").send_keys("option test number 1")
        self.driver.find_element(By.ID, "id_options-1-number").click()
        self.driver.find_element(By.ID, "id_options-1-number").send_keys("2")
        self.driver.find_element(By.ID, "id_options-1-option").click()
        self.driver.find_element(
            By.ID, "id_options-1-option").send_keys("option test number 2")
        self.driver.find_element(By.NAME, "_save").click()
        self.driver.find_element(By.LINK_TEXT, "Voting").click()
        self.driver.find_element(By.LINK_TEXT, "Votings").click()
        self.driver.find_element(By.CSS_SELECTOR, ".addlink").click()
        self.driver.find_element(By.ID, "id_name").send_keys("name voting test")
        self.driver.find_element(By.ID, "id_themeVotation").click()
        dropdown = self.driver.find_element(By.ID, "id_themeVotation")
        dropdown.find_element(By.XPATH, "//option[. = 'Electoral']").click()
        self.driver.find_element(By.ID, "id_themeVotation").click()
        self.driver.find_element(By.ID, "id_preference").click()
        dropdown = self.driver.find_element(By.ID, "id_preference")
        dropdown.find_element(By.XPATH, "//option[. = 'High']").click()
        self.driver.find_element(By.ID, "id_preference").click()
        self.driver.find_element(By.ID, "id_desc").click()
        self.driver.find_element(By.ID, "id_desc").send_keys("desc test")
        self.driver.find_element(By.ID, "id_question").click()
        dropdown = self.driver.find_element(By.ID, "id_question")
        dropdown.find_element(
            By.XPATH, "//option[. = 'desc question test']").click()
        self.driver.find_element(By.ID, "id_question").click()
        self.driver.find_element(By.ID, "id_auths").click()
        dropdown = self.driver.find_element(By.ID, "id_auths")
        dropdown.find_element(
            By.XPATH, "//option[. = 'http://localhost:8000']").click()
        self.driver.find_element(By.NAME, "_save").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Start']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Stop']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        elements = self.driver.find_elements(By.XPATH, "//td[5]")
        assert len(elements) > 0
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Restart']").click()
        elements = self.driver.find_elements(By.XPATH, "//td[5]")
        assert len(elements) == 0
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(
            By.XPATH, "//option[. = 'Delete selected votings']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
        self.driver.find_element(By.LINK_TEXT, "Voting").click()
        self.driver.find_element(By.LINK_TEXT, "Questions").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(
            By.XPATH, "//option[. = 'Delete selected questions']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()

    def test_testtallydownloadtxt(self):

        self.driver.get("http://localhost:8000/admin/")
        self.driver.set_window_size(957, 727)
        self.driver.find_element(By.ID, "id_username").send_keys(self.usernameDecide)
        self.driver.find_element(By.ID, "id_password").send_keys(self.passwordDecide)
        self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".model-question .addlink").click()
        self.driver.find_element(By.ID, "id_desc").send_keys("question test")
        self.driver.find_element(By.CSS_SELECTOR, ".field-scopes").click()
        self.driver.find_element(By.ID, "id_scopes").click()
        dropdown = self.driver.find_element(By.ID, "id_scopes")
        dropdown.find_element(By.XPATH, "//option[. = 'Literature']").click()
        self.driver.find_element(By.ID, "id_scopes").click()
        self.driver.find_element(By.ID, "id_options-0-number").click()
        self.driver.find_element(By.ID, "id_options-0-number").send_keys("1")
        self.driver.find_element(By.ID, "id_options-0-option").click()
        self.driver.find_element(
            By.ID, "id_options-0-option").send_keys("test well")
        self.driver.find_element(By.ID, "id_options-1-number").click()
        self.driver.find_element(By.ID, "id_options-1-number").send_keys("3")
        self.driver.find_element(By.ID, "id_options-1-option").click()
        self.driver.find_element(By.ID, "id_options-1-number").click()
        self.driver.find_element(By.ID, "id_options-1-number").send_keys("2")
        self.driver.find_element(By.ID, "id_options-1-option").click()
        self.driver.find_element(
            By.ID, "id_options-1-option").send_keys("test bad")
        self.driver.find_element(By.NAME, "_save").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Votings").click()
        self.driver.find_element(By.CSS_SELECTOR, ".addlink").click()
        self.driver.find_element(By.ID, "id_name").send_keys("test voting")
        self.driver.find_element(By.ID, "id_themeVotation").click()
        dropdown = self.driver.find_element(By.ID, "id_themeVotation")
        dropdown.find_element(By.XPATH, "//option[. = 'Electoral']").click()
        self.driver.find_element(By.ID, "id_themeVotation").click()
        self.driver.find_element(By.ID, "id_preference").click()
        dropdown = self.driver.find_element(By.ID, "id_preference")
        dropdown.find_element(By.XPATH, "//option[. = 'High']").click()
        self.driver.find_element(By.ID, "id_preference").click()
        self.driver.find_element(By.ID, "id_desc").click()
        self.driver.find_element(By.ID, "id_desc").send_keys("desc test")
        dropdown = self.driver.find_element(By.ID, "id_auths")
        dropdown.find_element(
            By.XPATH, "//option[. = 'http://localhost:8000']").click()
        self.driver.find_element(By.ID, "id_question").click()
        dropdown = self.driver.find_element(By.ID, "id_question")
        dropdown.find_element(By.XPATH, "//option[. = 'question test']").click()
        self.driver.find_element(By.ID, "id_question").click()
        self.driver.find_element(By.NAME, "_save").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Start']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Start']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Stop']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Tally']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(
            By.XPATH, "//option[. = 'ExportTallyToFile']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Questions").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(
            By.XPATH, "//option[. = 'Delete selected questions']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Votings").click()
        self.driver.find_element(By.CSS_SELECTOR, ".breadcrumbs").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Questions").click()

    def test_testtallydownloadzip(self):
        self.driver.get("http://localhost:8000/admin/")
        self.driver.set_window_size(957, 727)
        self.driver.find_element(
            By.ID, "id_username").send_keys(self.usernameDecide)
        self.driver.find_element(
            By.ID, "id_password").send_keys(self.passwordDecide)
        self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".model-question .addlink").click()
        self.driver.find_element(By.ID, "id_desc").send_keys("question test")
        self.driver.find_element(By.CSS_SELECTOR, ".field-scopes").click()
        self.driver.find_element(By.ID, "id_scopes").click()
        dropdown = self.driver.find_element(By.ID, "id_scopes")
        dropdown.find_element(By.XPATH, "//option[. = 'Literature']").click()
        self.driver.find_element(By.ID, "id_scopes").click()
        self.driver.find_element(By.ID, "id_options-0-number").click()
        self.driver.find_element(By.ID, "id_options-0-number").send_keys("1")
        self.driver.find_element(By.ID, "id_options-0-option").click()
        self.driver.find_element(
            By.ID, "id_options-0-option").send_keys("test well")
        self.driver.find_element(By.ID, "id_options-1-number").click()
        self.driver.find_element(By.ID, "id_options-1-number").send_keys("3")
        self.driver.find_element(By.ID, "id_options-1-option").click()
        self.driver.find_element(By.ID, "id_options-1-number").click()
        self.driver.find_element(By.ID, "id_options-1-number").send_keys("2")
        self.driver.find_element(By.ID, "id_options-1-option").click()
        self.driver.find_element(
            By.ID, "id_options-1-option").send_keys("test bad")
        self.driver.find_element(By.NAME, "_save").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Votings").click()
        self.driver.find_element(By.CSS_SELECTOR, ".addlink").click()
        self.driver.find_element(By.ID, "id_name").send_keys("test voting")
        self.driver.find_element(By.ID, "id_themeVotation").click()
        dropdown = self.driver.find_element(By.ID, "id_themeVotation")
        dropdown.find_element(By.XPATH, "//option[. = 'Electoral']").click()
        self.driver.find_element(By.ID, "id_themeVotation").click()
        self.driver.find_element(By.ID, "id_preference").click()
        dropdown = self.driver.find_element(By.ID, "id_preference")
        dropdown.find_element(By.XPATH, "//option[. = 'High']").click()
        self.driver.find_element(By.ID, "id_preference").click()
        self.driver.find_element(By.ID, "id_desc").click()
        self.driver.find_element(By.ID, "id_desc").send_keys("desc test")
        dropdown = self.driver.find_element(By.ID, "id_auths")
        dropdown.find_element(
            By.XPATH, "//option[. = 'http://localhost:8000']").click()
        self.driver.find_element(By.ID, "id_question").click()
        dropdown = self.driver.find_element(By.ID, "id_question")
        dropdown.find_element(By.XPATH, "//option[. = 'question test']").click()
        self.driver.find_element(By.ID, "id_question").click()
        self.driver.find_element(By.NAME, "_save").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Start']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Start']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Stop']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Tally']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(
            By.XPATH, "//option[. = 'ExportTallyToFile']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Questions").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(
            By.XPATH, "//option[. = 'Delete selected questions']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Votings").click()
        self.driver.find_element(By.CSS_SELECTOR, ".breadcrumbs").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Questions").click()

    def test_testtallyexport(self):
        self.driver.get("http://localhost:8000/admin/")
        self.driver.set_window_size(957, 727)
        self.driver.find_element(
            By.ID, "id_username").send_keys(self.usernameDecide)
        self.driver.find_element(
            By.ID, "id_password").send_keys(self.passwordDecide)
        self.driver.find_element(By.LINK_TEXT, "Questions").click()
        self.driver.find_element(By.CSS_SELECTOR, ".addlink").click()
        self.driver.find_element(By.ID, "id_desc").send_keys("desc test question")
        self.driver.find_element(By.ID, "id_scopes").click()
        element = self.driver.find_element(By.ID, "id_scopes")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "id_scopes").click()
        dropdown = self.driver.find_element(By.ID, "id_scopes")
        dropdown.find_element(By.XPATH, "//option[. = 'Literature']").click()
        self.driver.find_element(By.ID, "id_scopes").click()
        self.driver.find_element(By.ID, "id_options-0-number").click()
        self.driver.find_element(By.ID, "id_options-0-number").send_keys("1")
        self.driver.find_element(By.ID, "id_options-0-option").click()
        self.driver.find_element(
            By.ID, "id_options-0-option").send_keys("test op 1")
        self.driver.find_element(By.ID, "id_options-1-number").click()
        self.driver.find_element(By.ID, "id_options-1-number").send_keys("2")
        self.driver.find_element(By.ID, "id_options-1-option").click()
        self.driver.find_element(
            By.ID, "id_options-1-option").send_keys("test op 2")
        self.driver.find_element(By.NAME, "_save").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Votings").click()
        self.driver.find_element(By.CSS_SELECTOR, ".addlink").click()
        self.driver.find_element(By.ID, "id_name").send_keys("prueba test voting")
        self.driver.find_element(By.ID, "id_themeVotation").click()
        dropdown = self.driver.find_element(By.ID, "id_themeVotation")
        dropdown.find_element(By.XPATH, "//option[. = 'Electoral']").click()
        self.driver.find_element(By.ID, "id_themeVotation").click()
        self.driver.find_element(By.ID, "id_preference").click()
        element = self.driver.find_element(By.ID, "id_preference")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "id_preference").click()
        dropdown = self.driver.find_element(By.ID, "id_preference")
        dropdown.find_element(By.XPATH, "//option[. = 'High']").click()
        self.driver.find_element(By.ID, "id_preference").click()
        self.driver.find_element(By.ID, "id_desc").click()
        self.driver.find_element(By.ID, "id_desc").send_keys("desc test")
        self.driver.find_element(By.ID, "id_question").click()
        dropdown = self.driver.find_element(By.ID, "id_question")
        dropdown.find_element(
            By.XPATH, "//option[. = 'desc test question']").click()
        self.driver.find_element(By.ID, "id_question").click()
        dropdown = self.driver.find_element(By.ID, "id_auths")
        dropdown.find_element(
            By.XPATH, "//option[. = 'http://localhost:8000']").click()
        self.driver.find_element(By.NAME, "_save").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Start']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(By.XPATH, "//option[. = 'Stop']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(
            By.XPATH, "//option[. = 'ExportTallyToFile']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(
            By.XPATH, "//option[. = 'Delete selected votings']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Questions").click()
        self.driver.find_element(By.NAME, "_selected_action").click()
        self.driver.find_element(By.NAME, "action").click()
        dropdown = self.driver.find_element(By.NAME, "action")
        dropdown.find_element(
            By.XPATH, "//option[. = 'Delete selected questions']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "index").click()
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
